### ISSUE TITLE
System Exception if [mod_folder]_DLTX is present

### ISSUE THREAD

**Issue by themrdemonized** [MerelyMezz/LTXDiff#1]
If [mod_folder]_DLTX is already present in mod directory (for example if use dltxify command again in case of changes), this error is thrown:

```
Unhandled exception. System.Exception: Exception of type 'System.Exception' was thrown.
   at LTXDiff.Routines.DLTXify(String BaseDir, String ModDir, String ModName)
   at LTXDiff.Program.Main(String[] args)
```

**Comment by MerelyMezz** [comment]
This is an intended safety measure, to prevent unintentional overwrites. If you have need for it, I could implement it as a switch instead, I was just lazy at the time. Though I would recommend deleting the previous folder in any case, since dltxify doesn't delete stale files.

**Comment by themrdemonized** [comment]
If thats intended i guess its better to catch that so it wouldn't show error popup window, might give a confusion of whats actually happening. Or adding some kind of "-overwrite" argument to force overwrite.

**Comment by MerelyMezz** [comment]
Yea I suppose I should at the very least print a human readable error message, instead of throwing a generic exception. Like I said, I was being lazy.

**Comment by MerelyMezz** [comment]
Addressed in https://github.com/MerelyMezz/LTXDiff/commit/2229fd786688a8a20906b204b38870255517d084
