### ISSUE TITLE
Create new segments via DLTX

### ISSUE THREAD

**Issue by EnderWiggin** [MerelyMezz/LTXDiff#5]
Maybe I've done it wrong, but I couldn't find a way to add new section through DLTX. If I just add [section] without ! into a mod_*.ltx file it is not seen by the game.
I couldn't find a way to add new upgrade definition file without editing some existing file with bunch of imports and if DLTX could add new sections it would greatly assist in this.

**Comment by MerelyMezz** [comment]
You can absolutely add new sections with DLTX, you likely just made a mistake somewhere along the way. Without knowing any details about what you are trying to do, I suggest making your mod "conventionally" (i.e. directly editing the files you would without using DLTX format) first, and then using DLTXify to generate your mod. It should come out correctly.

**Comment by EnderWiggin** [comment]
Ok, I'll describe steps that I've tried. I want to add some upgrades to PDA. Made `configs/mod_system_xxx.ltx` where modified `[device_pda_3]` to have some upgrade definitions by adding `upgrades = up_gr_firstab_pdac` line:
```
![device_pda_3]
upgrades                    = up_gr_firstab_pdac
```
 Then put my custom upgrades at the end of `configs/items/weapons/upgrades/w_walther_up.ltx` that was copied from base files:
```
[up_sect_firsta_pda_c]
cost                                     = 10000
value                                    = 0

[up_sect_firstс_pda_c]
cost                                     = 20000
value                                    = 0

[up_firsta_pdac]
scheme_index = 0, 0
known = 1
effects = up_gr_firstcd_pdac
section = up_sect_firsta_pda_c
property = prop_binoc_autolock
precondition_functor = inventory_upgrades.precondition_functor_a
precondition_parameter = true
effect_functor = inventory_upgrades.effect_functor_a
effect_parameter = something_here
prereq_functor = inventory_upgrades.prereq_functor_a
prereq_tooltip_functor = inventory_upgrades.prereq_tooltip_functor_a
prereq_params = 
name = st_up_pda3_a1_name
description = st_up_pda3_a1_descr
icon = ui_inGame2_upgrade_binoc_4_1

[up_firstc_pdac]
scheme_index = 1, 0
known = 1
effects = 
section = up_sect_firstс_pda_c
property = prop_binoc_autolock
precondition_functor = inventory_upgrades.precondition_functor_a
precondition_parameter = true
effect_functor = inventory_upgrades.effect_functor_a
effect_parameter = something_here
prereq_functor = inventory_upgrades.prereq_functor_a
prereq_tooltip_functor = inventory_upgrades.prereq_tooltip_functor_a
prereq_params = 
name = st_up_pda3_a2_name
description = st_up_pda3_a2_descr
icon = ui_inGame2_upgrade_binoc_2_2

[up_gr_firstab_pdac]
elements = up_firsta_pdac

[up_gr_firstcd_pdac]
elements = up_firstc_pdac
```
This works perfectly fine in game - I see those upgrades and can install them. When I tried dltxifying that file it created `configs/items/mod_item_base_xxx.ltx` with my custom lines. Game crashes on load if I use that mod file instead of walther one - says it can't find `[up_gr_firstab_pdac]` section.
I noticed that `configs/weapons/base.ltx` has generic `#include w_*.ltx`, so I've created new file `configs/items/weapons/w_pda_xxx.ltx` and put my custom upgrade lines there. With this change game loads, but crashes when hovering over new upgrades ans says it can't find `[up_sect_firsta_pda_c]` section.

**Comment by MerelyMezz** [comment]
DLTXifying `configs/items/weapons/upgrades/w_walther_up.ltx` should have resulted in different files being produced.

![cmd_0Wav6v2U1R](https://user-images.githubusercontent.com/5637889/142632037-8a062305-a8a9-48d7-a0d3-93aeb4e172c9.png)

Are you sure the directories you are pointing LTXDiff to are properly set up? Both your `_unpacked` and mod directory should contain a `gamedata` folder, otherwise LTXDiff won't be able to properly match them.

Also if an LTX file belongs to multiple root files, you will have to make multiple mod files with the same changes. It's likely your changes made it to `system.ltx`, but not `item_upgrades`, which I imagine is the one that's important here.

**Comment by EnderWiggin** [comment]
Oh, apparently my unpacked folder had some missing files. I've re-unpacked it and now it worked properly. Thanks for the help!
